theme = "typography-theme"
languageCode = "en-us"
baseurl = "https://hotpotatoes.vc/"
title = "Hot Potatoes"

author = "Irfan Shah"
copyright = "Copyright © 2019, Hot Potatoes LLP, all rights reserved."

[params]
    name = "Hot Potatoes"
    description = "Hot Potatoes website buit with Hugo and Tailwindcss."
    favicon = "favicon.ico"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
